services:
  react_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:5173" 
    volumes:
       - ./frontend:/app
       - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - app-network

  laravel_app:
    build:
      context: ./backend/laravel
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./backend/laravel/:/var/www
    depends_on:
      - mysql_db
    networks:
      - app-network  

  node_nl2sql_service:
   build: 
    context: ./backend/node/nl2sql_service
    dockerfile: Dockerfile
   container_name: node_nl2sql_service
   ports: 
    - "4000:4000"
   volumes:
    - ./backend/node/nl2sql_service:/app
    -  /app/node_modules
   stdin_open: true
   tty: true
   networks:
      - app-network

  mysql_db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ai_job_hunt
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: arulmurugan
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network


  scrapper_bot:
    build:
      context: ./scrapper_bot
    container_name: scrapper_bot
    volumes:
      - ./scrapper_bot:/app
    depends_on:
      - nginx
    networks:
      - app-network 


  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend/laravel:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - laravel_app
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network: